version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      # - data:/var/lib/postgresql/data
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    expose:
      - "5432"
    ports:
      - "5432:5432"
